library(shiny)

navbarPage(
  theme = shinytheme("united"),
  title = 'MALTEM costing application',
  tabPanel('Home',
           h1('Mozambican Alliance Towards the Elimination of Malaria'),
           h2('Health Economics Unit'),
           h2('laia.cirera@isglobal.org')),
  tabPanel('Static',
           h1('Aggregated costs by category'),
           fluidRow(column(6,
                           selectInput('currency',
                                       'Currency',
                                       choices = c('MZN', 'USD')),
                           checkboxGroupInput('year',
                                              'Year',
                                              choices = 2015:2017,
                                              selected = 2015:2017),
                           selectInput('group_variable',
                                       'Group by',
                                       choices = c('Elimination activity' = 'elimination_activity',
                                                   'Budget category' = 'budget_category',
                                                   'Capital vs. current' = 'capital_vs_current',
                                                   'Financial vs. non-financial' = 'financial_vs_non_financial')),
                           uiOutput('filter')),
                    column(6,
                           plotOutput('bars'),
                           DT::dataTableOutput('bars_table')
                           # plotOutput('g'),
                           ))),
  tabPanel('Projections',
           fluidRow(column(6,
                           sliderInput('year_animate',
                                       'Year',
                                       min = 2015,
                                       max = 2035,
                                       value = 2015,
                                       step = 1,
                                       animate = animationOptions(interval = 400,
                                                                  loop = FALSE,
                                                                  playButton = NULL,
                                                                  pauseButton = NULL)),
                           checkboxInput('cumulative',
                                         'Show cumulative?',
                                         value = FALSE),
                           selectInput('currency_for_time',
                                       'Currency',
                                       choices = c('MZN', 'USD'),
                                       selected = 'USD'),
                           sliderInput('discount_rate',
                                       'Discount rate',
                                       min = 0,
                                       max = 15,
                                       value = 3),
                           sliderInput('inflation_rate',
                                       'Inflation rate',
                                       min = 0, 
                                       max = 15,
                                       value = 3)),
                    column(6,
                           plotOutput('time_chart'),
                           h3('Cumulative costs over 20 years'),
                           DT::dataTableOutput('time_table'),
                           h3('Year specific costs'),
                           DT::dataTableOutput('time_table_yearly')
                           # htmlOutput('motion_chart')
                           ))),
  tabPanel('Outcomes',
           fluidRow(
             column(3,
                    selectInput('intervention',
                                'Intervention',
                                choices = c('MDA',
                                            'REACT',
                                            'LLIN',
                                            'IRS')),
                    uiOutput('cost_per_output_indicator_input')),
             column(4,
                    h1(textOutput('text1')),
                    h3(textOutput('text2')),
                    plotOutput('simple_plot')),
             column(5, 
                   plotOutput('plot1'),
                    tableOutput('table3'),
                    h3(textOutput('text4'))))))